### PR TITLE
Fix: update  verse filter placeholder and select options

### PR DESCRIPTION
**Pull request by Hamza-nabil**
This PR updates verse filter.

- [x] **Updated the placeholder text from Filter by surah to Filter by ayah** : The previous placeholder was misleading, as it referred to filtering by surah when the actual input is for filtering by ayah. example from [Ayah translation proofreading](https://qul.tarteel.ai/translation_proofreadings)

    image

- [x] Updated the verse filter to default to 1..286

### CODE REVIEW

**Comment by piraka9011** [comment]
JAK for the PR!
I think a better approach is to make this field dynamic.

SheikhGPT recommends [this approach](https://chatgpt.com/share/66edec29-acb4-800e-a119-0fe5c65e0da1)

I'll defer to @naveed-ahmad though in case he has a better approach or if we want to follow up this PR with making it dynamic since it's a step in the right direction.

**Comment by Hamza-nabil** [comment]
JAK for the feedback! 

I agree with you making the filled dynamic is the right choice. 

The suggested approach seems promising. perhaps we can benefit from the `Chapter` class by adding `verse_count` method to use in the verse filter.

**Comment by naveed-ahmad** [comment]
JazakAllah kharain for contributing @Hamza-nabil 

I'll like to suggest three changes, maybe in separate PRs:

- Move the ayah and surah filters to a shared partial, most tools are using surah and ayah filters. This will remove a lot of duplicates. 
- Change the surah filters to render both surah name and number, this will improve the surah search
```
<% 
chapters = Chapter.order('id asc').map do |c| 
  [c.humanize, c.id]
end
%>

<%= select_tag :filter_chapter, options_for_select(chapters, params[:filter_chapter]), include_blank: true, class: 'form-select', data: { controller: 'select2' } %>
```

- Use Stimilus controller to populate ayah filters, the gpt links shared by @piraka9011 has the basic stuff you need. But it's not refreshing the select2 after populating the ayahs. 

Feel free to ping me here or on discord if you need any help.

**Comment by Hamza-nabil** [comment]
Thank you ! I will made the necessary changes and create a new PR

**Pull request closed without merging**
